ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view()),
    path('ads', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create', views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update', views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete', views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite', views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
    path('ad/requestforlogin', views.ReqView.as_view(success_url=reverse_lazy('ads:all')), name='req'),
    path('ads/pf',views.portfolioView.as_view(), name='basic'),
]

djnew/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    #path('', include('home.urls')),  # Change to ads.urls
    path('', include('ads.urls')), #<-- for ads assignment
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep


    #path('', views.ads, name='ads'),
    path('ads/', include('ads.urls')),
    path('polls/', include('polls.urls')),

    # Sample applications
    # path('hello/', include('hello.urls')),
    # path('users/', include('users.urls')),
    # path('tracks/', include('tracks.urls')),
    # path('views/', include('views.urls')),
    # path('route/', include('route.urls', namespace='nsroute')),
    # path('tmpl/', include('tmpl.urls')),
    # path('gview/', include('gview.urls')),
    # path('session/', include('session.urls')),
    # path('authz/', include('authz.urls')),
    # path('getpost/', include('getpost.urls')),
    # path('form/', include('form.urls')),
    # path('crispy/', include('crispy.urls')),
    # path('myarts/', include('myarts.urls')),
    # path('menu/', include('menu.urls')),
    # path('forums/', include('forums.urls')),
    # path('pics/', include('pics.urls')),
    # path('favs/', include('favs.urls')),
    # path('favsql/', include('favsql.urls')),
    # path('rest/', include('rest.urls')),
    # path('autos/', include('autos.urls')),
    # path('usermodel/', include('usermodel.urls')),
    # path('chat/', include('chat.urls')),
    # path('util/', include('util.urls')),
    # path('well/', include('well.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
           'show_indexes': True},
        name='site_path'
    ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
        path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
    )
    print('Using',social_login,'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

ads/forms.py
from django import forms
from ads.models import Ad, Contact
from django.core.files.uploadedfile import InMemoryUploadedFile
from ads.humanize import naturalsize
# comment header
from django.core.exceptions import ValidationError
from django.core import validators

# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'ad'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Ad
        fields = ['title', 'text', 'price', 'picture']  # Picture is manual

    # Validate the size of the picture
    def clean(self) :
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None : return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True) :
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read();
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance


# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)


class ContactForm(forms.ModelForm):
    required_css_class = 'required'
    class Meta:
        model = Contact
        fields = '__all__'


# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

ads/views.py
from ads.models import Ad, Comment, Fav, Contact
from ads.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
from ads.forms import CreateForm, CommentForm

from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.uploadedfile import InMemoryUploadedFile

from django.core.mail import send_mail
from django.conf import settings
from ads.forms import ContactForm
#from ads.contact import ContactForm

from ads.utils import dump_queries
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q

# class AdListView(OwnerListView):
#     model = Ad
#     template_name = "ads/ad_list.html"

#     def get(self, request) :
#         ad_list = Ad.objects.all()
#         favorites = list()
#         if request.user.is_authenticated:
#             # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
#             rows = request.user.favorite_ads.values('id')
#             # favorites = [2, 4, ...] using list comprehension
#             favorites = [ row['id'] for row in rows ]
#         ctx = {'ad_list' : ad_list, 'favorites': favorites}
#         return render(request, self.template_name, ctx)

class portfolioView(View):
    template_name = "ads/basic.html"

    def get(self, request):
        template_name = "ads/basic.html"
        return render(request, self.template_name)


class AdListView(View):
    template_name = "ads/ad_list.html"

    def get(self, request) :
        strval =  request.GET.get("search", False)

        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_ads.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]

        if strval :
            # Simple title-only search
            # objects = Post.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            query = Q(title__contains=strval)
            query.add(Q(text__contains=strval), Q.OR)
            objects = Ad.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else :
            # try both versions with > 4 posts and watch the queries that happen
            objects = Ad.objects.all().order_by('-updated_at')[:10]
            # objects = Post.objects.select_related().all().order_by('-updated_at')[:10]

        # Augment the post_list
        for obj in objects:
            obj.natural_updated = naturaltime(obj.updated_at)

        ctx = {'ad_list' : objects, 'favorites': favorites, 'search': strval}
        retval = render(request, self.template_name, ctx)

        dump_queries()
        return retval;


class ReqView(View):
    model = Ad
    success_url = reverse_lazy('ads:all')
    template_name = "ads/req.html"
    sub = "Request for login credentials"
    msg = "Thanks for contacting :)"
    msg += "\n"
    msg += "We will get back to as soon as possible !"
    from_email = settings.EMAIL_HOST_USER
    success_url = reverse_lazy('ads:all')
    to_email = [settings.EMAIL_HOST_USER]
    submitted = 0


    def get(self, request) :
        form = ContactForm()
        if 'submitted' in request.GET:
            submitted = 1
        else :
            submitted = 0
        ctx = {'form': form, 'submitted': submitted}
        return render(request, self.template_name, ctx)


    def post(self, request):
        form = ContactForm(request.POST)
        submitted = 0
        if form.is_valid():
            cd = form.cleaned_data
            items = Contact.objects.all()
            t = {'email': cd['email']}
            if t in items.values('email'):
                submitted = 2
                ctx = {'form': form, 'submitted': submitted}
                return render(request, self.template_name, ctx)
            else:
                form.save()
                # assert False
                m = "Credentials you want for your account -->"
                m += '\n' + "User Name : " + cd['username'] + '\n' + "Email : " + cd['email'] + '\n' + 'Password to set : ' + cd['password'] + '\n' + 'How do you know about me : ' + cd['source'] + '\n' + '\n' + '\n' + self.msg
                self.to_email.append(cd['email'])
                send_mail(self.sub, m, self.from_email, self.to_email, fail_silently=True)
            return HttpResponseRedirect('requestforlogin?submitted=True')
        else:
            ctx = {'form': form, 'submitted': submitted}
            return render(request, self.template_name, ctx)


class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = "ads/ad_detail.html"
    def get(self, request, pk) :
        x = Ad.objects.get(id=pk)
        comments = Comment.objects.filter(ad=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = { 'ad' : x, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, context)


class AdCreateView(LoginRequiredMixin, View):
    # model = Ad
    # fields = ['title', 'price', 'text']
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')


    def get(self, request, pk=None) :
        form = CreateForm()
        ctx = { 'form': form }
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None) :
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        pic = form.save(commit=False)
        pic.owner = self.request.user
        pic.save()
        return redirect(self.success_url)

class AdUpdateView(LoginRequiredMixin, View):
    # model = Ad
    # fields = ['title', 'price', 'text']
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')


    def get(self, request, pk) :
        pic = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(instance=pic)
        ctx = { 'form': form }
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None) :
        pic = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=pic)

        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template_name, ctx)

        pic = form.save(commit=False)
        pic.save()

        return redirect(self.success_url)

class AdDeleteView(OwnerDeleteView):
    model = Ad


def stream_file(request, pk) :
    pic = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = pic.content_type
    response['Content-Length'] = len(pic.picture)
    response.write(pic.picture)
    return response


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        f = get_object_or_404(Ad, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=f)
        comment.save()
        return redirect(reverse('ads:ad_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "ads/comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        ad = self.object.ad
        return reverse('ads:ad_detail', args=[ad.id])


# csrf exemption in class based views
# https://stackoverflow.com/questions/16458166/how-to-disable-djangos-csrf-validation
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Add PK",pk)
        t = get_object_or_404(Ad, id=pk)
        fav = Fav(user=request.user, ad=t)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Delete PK",pk)
        t = get_object_or_404(Ad, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, ad=t).delete()
        except Ad.DoesNotExist as e:
            pass

        return HttpResponse()

# class PicCreateView(LoginRequiredMixin, View):
#     template_name = 'pics/form.html'
#     success_url = reverse_lazy('pics:all')
#     def get(self, request, pk=None) :
#         form = CreateForm()
#         ctx = { 'form': form }
#         return render(request, self.template_name, ctx)

#     def post(self, request, pk=None) :
#         form = CreateForm(request.POST, request.FILES or None)

#         if not form.is_valid() :
#             ctx = {'form' : form}
#             return render(request, self.template_name, ctx)

#         # Add owner to the model before saving
#         pic = form.save(commit=False)
#         pic.owner = self.request.user
#         pic.save()
#         return redirect(self.success_url)

# class PicUpdateView(LoginRequiredMixin, View):
#     template_name = 'pics/form.html'
#     success_url = reverse_lazy('pics:all')
#     def get(self, request, pk) :
#         pic = get_object_or_404(Pic, id=pk, owner=self.request.user)
#         form = CreateForm(instance=pic)
#         ctx = { 'form': form }
#         return render(request, self.template_name, ctx)

#     def post(self, request, pk=None) :

ads/templates/ads/ad_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Vlog</h1>

<p>Are you sure you want to delete the vlog: {{ ad }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <a href="{% url 'ads:ad_detail'  ad.id %}"><input type="button" value="Cancel"></a>
</form>
{% endblock %}

ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}

{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
<style>
body {
    font-family : Tahoma, Geneva, sans-serif;
}
.overlay{
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 20;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
.commentclass{
    font-family:sans-serif;
    color : #f5c133;
    font-size:11px;
    text-shadow: 0.7px 0.7px black;
}
</style>
{% endblock %}
{% block content %}
<span style="float: right;">
<p>({{ ad.updated_at|naturaltime }})</p>
{% if ads.owner == user %}
<a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ ad.title }}</h1>

{% if ad.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick=" document.getElementById('overlay').style.display = 'none'; " >/*  document.body.style.backgroundColor = 'rgba(0,0,0,0.5)';  */
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'ads:ad_picture' ad.id %}">
</div>
{% endif %}


<br>
<!--<h1>{{ ad.price }}</h1>-->

{% if ad.content_type %}
<div style="text-align: justify;text-justify: inter-word;">
<img style="float:right; max-width:47%;" src="{% url 'ads:ad_picture' ad.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
    </div>
{% endif %}

<p><div style="padding-top: 50px;
  padding-right: 50%;
  padding-bottom: 50px;
  padding-left: 10px;
  text-align: justify;
  text-justify: inter-word;">
{{ ad.text }}
</div></p>
<p>

{% if user.is_authenticated %}
<p>
{% load crispy_forms_tags %}
{% if ad.owner_id == user.id %}
        (<a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |
        <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>)
{% endif %}
</p>
<br clear="all"/>
<p>
<form method="post" action="{% url 'ads:ad_comment_create' ad.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="All Vlogs" onclick="window.location.href='{% url 'ads:all' %}';return false;">
</form>
</p>
{% endif %}
{% for comment in comments %}
<p> {{ comment.text }}
({{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'ads:ad_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a><span class="commentclass">&nbsp&nbspposted by you.</span>
{% else %}<span class="commentclass">&nbsp&nbsp posted by {{ comment.owner}}</span>
{% endif %}
</p>
{% endfor %}

</p>
<p>
<a href="{% url 'ads:all' %}">All Vlogs</a>
</p>
{% endblock %}

ads/templates/ads/ad_form.html
{% extends "base_menu.html" %}

{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}';return false;">
  </form>
</p>
<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}

{% block content %}
<h1>Vlogs</h1>
<div style="float:right">
<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}
  >
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'ads:all' %}"><i class="fa fa-undo"></i></a>
</form>
</div>
<p>
{% if ad_list %}
<ul>
  {% for ad in ad_list %}
    <li>
        <a href="{% url 'ads:ad_detail'  ad.id %}">{{ ad.title }}</a>
        {% if ad.owner_id == user.id %}
        (<a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |
        <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>)
        {% endif %}
        {% if user.is_authenticated %}
        <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
        <a href="#" onclick=
            "favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }} );return false;"
            {% if ad.id not in favorites %} style="display: none;" {% endif %}
            id="favorite_star_{{ad.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        <!-- the second href -->
        <a href="#" onclick=
             "favPost('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} );return false;"
            {% if ad.id in favorites %} style="display: none;" {% endif %}
            id="unfavorite_star_{{ad.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        {% endif %}
        <br/>
        <div style="left:10px">
            {% if ad.text|length < 100 %}
                {{ ad.text }}
            {% else %}
                {{ ad.text|slice:"0:99" }}
                <a href="{% url 'ads:ad_detail'  ad.id %}">...</a>
            {% endif %}
        </div>
        <small>
        {% if ad.owner.username %}
            posted by {{ ad.owner.username }}
        {% endif %}
        {{ ad.natural_updated }}
        </small>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no Vlogs in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'ads:ad_create' %}">Add a Vlog</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
<br><br>
<br>
<a href="{% url 'ads:req' %}">Request for Login credentials</a>
{% endif %}
</p>
<script>
function favPost(url, ad_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+ad_id).toggle();
        $("#favorite_star_"+ad_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
{% endblock %}

ads/templates/ads/ad_listOfFav.html
{% extends "base_menu.html" %}


{% block content %}
<h1>Ads</h1>
<p>
{% if ad_list %}
<ul>
  {% for ad in ad_list %}
    <li>
        <a href="{% url 'ads:ad_detail'  ad.id %}">{{ ad.title }}</a>
        {% if ad.owner_id == user.id %}
        (<a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |
        <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>)
        {% endif %}
        {% if user.is_authenticated %}
        <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
        <a href="#" onclick=
            "favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }} );return false;"
            {% if ad.id not in favorites %} style="display: none;" {% endif %}
            id="favorite_star_{{ad.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        <!-- the second href -->
        <a href="#" onclick=
             "favPost('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} );return false;"
            {% if ad.id in favorites %} style="display: none;" {% endif %}
            id="unfavorite_star_{{ad.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no ads in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'ads:ad_create' %}">Add a Ad</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
{% endif %}
</p>
<script>
function favPost(url, ad_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+ad_id).toggle();
        $("#favorite_star_"+ad_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
{% endblock %}

ads/templates/ads/comment_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'ads:ad_detail' comment.ad.id %}" class="btn btn-secondary"><input type="button" class="btn btn-secondary" value="Cancel"></a>
</form>
{% endblock %}

ads/templates/ads/req.html
{% extends "base_menu.html" %}
{% block title %}Contact Us{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<p>
<h1>Contact us</h1>
{% if user.is_authenticated %}
<p class="success">
    You are already Logged in :)<br>Please logout to request for another set of credentials !
</p>
{% else %}
{% if submitted == 1 %}
<p class="success">
  Your request was submitted successfully. Thank you.
</p>
{% elif submitted == 2 %}
<p class="success">
    Your mail has already been registed for Request !<br>Please wait for our Response if you don't get already verified :)<br /><br /><br />
    Please don't try multiple time it only wastes your time.
</p>
{% else %}
<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}';return false;">
</form>
{% endif %}
{% endif %}
</p>
{% endblock %}